config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]  # This handles new and create actions for enrollments
  end

  resources :users, only: [:index, :edit, :show, :update]

  root "home#index"
  get 'home/home'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :enrollments) }  
  validates :user, :course, presence: true

  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id  # User can't be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  # User can't be subscribed to the same course twice

  validate :cant_subscribe_to_own_course  # User can't create a subscription if course.user == current_user.id

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }

  
  # Define ransackable attributes
  def self.ransackable_attributes(auth_object = nil)
    ["id", "course_id", "created_at", "price", "rating", "review", "updated_at", "user_id"]
  end

  # Define ransackable associations
  def self.ransackable_associations(auth_object = nil)
    ["user", "course"]
  end

  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end

  end

  after_destroy do

    course.update_rating
  end

  protected

  def cant_subscribe_to_own_course
    if new_record? && user_id.present? && user_id == course.user_id
      errors.add(:base, "You can not subscribe to your own course")
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]
  before_action :set_course, only: [:new, :create]

  def my_students
    @ransack_path = my_students_enrollments_path  # Correct placement of the path
    @q = Enrollment.joins(:course).where(courses: { user: current_user }).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  def index
    @ransack_path = enrollments_path  # Correct placement of the path
    @q = Enrollment.ransack(params[:q]) # Fix: Initialize Ransack object
    @pagy, @enrollments = pagy(@q.result.includes(:user, :course)) # Search, sort, and paginate
    authorize @enrollments
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create
    if @course.price > 0
      flash[:alert] = "You cannot access paid courses yet."
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    end
  end

  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_course
      @course = Course.find(params[:course_id])
    end

    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="card">
  <div class="card-header">
    <i class="fa fa-user"></i>
    <%= link_to enrollment.user.username, user_path(enrollment.user) %>
    <i class="fa fa-clock"></i>
    <%= time_ago_in_words(enrollment.updated_at) %>
    <i class="fa fa-graduation-cap"></i>
    <%= link_to enrollment.course, course_path(enrollment.course) %>
  </div>
  
  <div class="card-body">
    <i class="text-warning fa fa-star"></i>
    <b><%= enrollment.rating %></b>
    <i class="fa fa-comment"></i>
    <small><%= enrollment.review %></small>
  </div>
  
  <% if current_user %>
    <div class="card-footer">
      <% if policy(enrollment).edit? %>
        <%= link_to 'Edit Review', edit_enrollment_path(enrollment) %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="card">
  <div class="card-header">
    <i class="fa fa-user"></i>
    <%= link_to enrollment.user.username, user_path(enrollment.user) %>
    <i class="fa fa-clock"></i>
    <%= time_ago_in_words(enrollment.updated_at) %>
    <i class="fa fa-graduation-cap"></i>
    <%= link_to enrollment.course, course_path(enrollment.course) %>
  </div>
  
  <div class="card-body">
    <i class="text-warning fa fa-star"></i>
    <b><%= enrollment.rating %></b>
    <i class="fa fa-comment"></i>
    <small><%= enrollment.review %></small>
  </div>
  
  <% if current_user %>
    <div class="card-footer">
      <% if policy(enrollment).edit? %>
        <%= link_to 'Edit Review', edit_enrollment_path(enrollment) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/enrollments/_form.html.erb
<%# frozen_string_literal: true %>
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.input :review %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<% content_for :title, "Edit Enrollment" %>

<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white text-center">
          <h4 class="mb-0">
            <i class="fa fa-edit"></i> Edit Enrollment
          </h4>
        </div>
        <div class="card-body">
          <%= form_with model: @enrollment, local: true, class: "needs-validation" do |f| %>
            <div class="form-group">
              <%= f.label :rating, "Rating", class: "form-label d-block" %>
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <% (1..5).each do |rating| %>
                  <label class="btn btn-outline-primary <%= 'active' if @enrollment.rating == rating %>">
                    <%= f.radio_button :rating, rating, checked: (@enrollment.rating == rating) %>
                    <%= rating %>
                  </label>
                <% end %>
              </div>
            </div>

            <div class="form-group mt-3">
              <%= f.label :review, "Review", class: "form-label" %>
              <%= f.text_area :review, rows: 3, class: "form-control", placeholder: "Write your review here...", required: true %>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <%= link_to "Back", enrollments_path, class: "btn btn-secondary btn-sm" %>
              <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/index.html.erb
<% content_for :title do %>
  Corsego | All Enrollments
<% end %>

<h3 class="text-center">
  Enrollments
  <span class="badge badge-info">
    <%= @enrollments.count %>
  </span>
</h3>

<p></p>

<%= search_form_for @q, url: @ransack_path do |f| %>
  <%= f.search_field :user_email_cont, placeholder: 'user email' %>
  <%= f.search_field :course_title_cont, placeholder: 'course title' %>
  <%= f.search_field :price_eq, placeholder: 'price' %>
  <%= f.search_field :rating_eq, placeholder: 'rating' %>
  <%= f.search_field :review_cont, placeholder: 'review' %>
  <%= f.submit %>
<% end %>

<%= link_to 'refresh', @ransack_path %>

<div class="table-responsive">
  <table class="table table-bordered table-striped table-sm">
    <thead>
      <tr>
        <th>ID</th>
        <th>
          <%= sort_link(@q, :user_email) %>
          <i class="fa fa-user"></i> User
        </th>
        <th>
          <%= sort_link(@q, :created_at) %>
          <i class="fa fa-clock"></i> <i class="fa fa-lock-open"></i> Bought
        </th>
        <th>
          <%= sort_link(@q, :course_title) %>
          <i class="fa fa-graduation-cap"></i> Course
        </th>
        <th>
          <%= sort_link(@q, :price) %>
          <i class="fa fa-dollar-sign"></i> Price
        </th>
        <th>
          <%= sort_link(@q, :updated_at) %>
          <span class="row text-warning"><i class="fa fa-clock"></i> Reviewed on</span>
        </th>
        <th>
          <%= sort_link(@q, :rating) %>
          <i class="text-warning fa fa-star"></i>
        </th>
        <th>
          <i class="text-warning fa fa-comment"></i> Review
        </th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
          <td><%= enrollment.id %></td>
          <td><%= link_to enrollment.user, user_path(enrollment.user) %></td>
          <td><%= enrollment.created_at.strftime("%d/%b/%Y, %H:%M") %></td>
          <td><%= link_to enrollment.course, course_path(enrollment.course) %></td>
          <td><%= number_to_currency(enrollment.price) %></td>
          <td>
            <% if enrollment.rating.present? %>
              <%= enrollment.updated_at.strftime("%d/%b/%Y, %H:%M") %>
            <% end %>
          </td>
          <td><%= enrollment.rating %></td>
          <td><%= enrollment.review %></td>
          <td><%= link_to 'See Review', enrollment %></td>
          <td><%= link_to 'Add Review', edit_enrollment_path(enrollment) %></td>
          <td><%= link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% pagy_bootstrap_nav(@pagy) %>
<br>

app/views/enrollments/new.html.erb
<% content_for :title do %>
  Corsego | New enrollment
<% end %>

<div class="card">
  <div class="card-header">
    <h3>
      <i class="fa fa-graduation-cap"></i>
      <%= link_to @course.title, course_path(@course) %>
    </h3>
    <hr />
    <i class="fa fa-lock-open"></i>
    Buy course
  </div>
  
  <div class="card-body">
    <%= form_tag course_enrollments_path(@course) do %>
      <%= submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success' %>
    <% end %>
  </div>
  
  <div class="card-footer">
    <%= link_to 'Back', course_path(@course) %>
  </div>
</div>

app/views/enrollments/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-sm">
        <div class="card-header bg-primary text-white p-2">
          <h5 class="mb-0">
            <i class="fas fa-graduation-cap"></i> Enrollment Details
          </h5>
        </div>
        <div class="card-body p-3">
          <!-- User Details -->
          <div class="mb-2">
            <h6>
              <i class="fas fa-user text-primary"></i> 
              <%= link_to @enrollment.user.email, user_path(@enrollment.user), class: 'text-dark text-decoration-none' %>
            </h6>
            <small class="text-muted">
              <i class="fas fa-clock"></i> Enrolled <%= time_ago_in_words(@enrollment.created_at) %> ago
            </small>
          </div>
          
          <!-- Course Details -->
          <div class="mb-2">
            <h6>
              <i class="fas fa-book text-primary"></i> 
              <%= link_to @enrollment.course.title, course_path(@enrollment.course), class: 'text-dark text-decoration-none' %>
            </h6>
            <span class="badge bg-success">
              <i class="fas fa-layer-group"></i> Level: <%= @enrollment.course.level %>
            </span>
          </div>
          
          <!-- Rating and Review -->
          <div>
            <h6>
              <i class="fas fa-star text-warning"></i> Rating: 
              <span class="text-dark"><%= @enrollment.rating %>/5</span>
            </h6>
            <p class="text-muted mb-0">
              <i class="fas fa-comment"></i> <%= @enrollment.review %>
            </p>
          </div>
        </div>

        <% if current_user %>
          <!-- Footer Buttons -->
          <div class="card-footer d-flex justify-content-between p-2">
            <% if policy(@enrollment).edit? %>
              <%= link_to 'Edit Review', edit_enrollment_path(@enrollment), class: 'btn btn-outline-primary btn-sm' %>
            <% end %>
            <%= link_to 'Back', enrollments_path, class: 'btn btn-outline-secondary btn-sm' %>
            <%#>= link_to 'delete', destroy_enrollment_path(@enrollment), data: { turbo_method: :delete}, class: 'btn btn-outline-danger btn-sm' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>