config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]  # This handles new and create actions for enrollments
  end

  resources :users, only: [:index, :edit, :show, :update]

  root "home#index"
  get 'home/home'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :lessons) }  
  has_many :user_lessons, dependent: :destroy
  
  validates :title, :content, :course, presence: true
  
  include PublicActivity::Model
  tracked owner: Proc.new { |_controller, model| model.owner }
  attr_accessor :owner # Allows explicit assignment of the owner

  has_rich_text :content

  def viewed(user)
    self.user_lessons.where(user: user).present?
    #self.user_lessons.where(user_id: [user.id], lesson_id: [self.id]).present
  end

  include RankedModel
  ranks :row_order, :with_same => :course_id


  def to_s
    title
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    
  end

  def new
    @lesson = Lesson.new
    @course = Course.find(params[:course_id])
  end

  def edit
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_lesson
      @course = Course.find(params[:course_id])
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :content)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= simple_form_for([@course, @lesson]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%# f.input :content %>
    <%= f.label :content %>
    <%= f.rich_text_area :content %>
    <p></p>

    <%# f.association :course %>
    <%# f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div class="card">
  <div class="card-header">
    <!-- Check if the lesson has been viewed by the current user -->
    <% if lesson.viewed(current_user) == true %>
      <span class="text-success far fa-check-square"></span> <!-- VIEWED -->
    <% else %>
      <span class="text-danger far fa-check-square"></span> <!-- NOT VIEWED -->
    <% end %>

    <!-- Link to the lesson's page -->
    <%= link_to lesson.title, course_lesson_path(@course, lesson) %>
  </div>

  <% if policy(lesson).show? %>
    <div class="card-body">
      <%= lesson.content %> <!-- Display lesson content if the user is authorized -->
    </div>
  <% end %>

  <% if policy(lesson).edit? %>
    <div class="card-footer">
      <!-- Edit and delete links if the user is authorized to edit the lesson -->
      <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' %>
      <%= link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
    </div>
  <% end %>
</div>

app/views/lessons/_lesson_preview.html.erb
<% if current_user %>
  <% if lesson.course.bought(current_user) || @course.user == current_user %>
    <% if lesson.viewed(current_user) == true %>
      <i class="text-success fa fa-check-square"></i>
    <% else %>
      <i class="text-danger fa fa-check-square"></i>
    <% end %>
  <% else %>
    <i class="fa fa-check-square"></i>
  <% end %>
  <%= link_to course_lesson_path(@course, lesson) do %>
    <!--= lesson.row_order -->
    <%= lesson.row_order_rank + 1 %>
    <%= lesson.title %>
  <% end %>
<% else %>
  <i class="fa fa-check-square"></i>
  <%= link_to course_lesson_path(@course, lesson) do %>
    <!--= lesson.row_order -->
    <%= lesson.row_order_rank + 1 %>
    <%= lesson.title %>
  <% end %>
<% end %>

<div class="float-right">
  <% if policy(lesson).edit? %>
    <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  <% end %>
</div>

app/views/lessons/edit.html.erb
<%= link_to 'Courses', courses_path %> |
<%= link_to @lesson.course.title, course_path(@lesson.course) %> |
<%= link_to @lesson.title, course_lesson_path(@course, @lesson) %> |
Editing lesson

<p></p>

<div class="card">
  <div class="card-header">
    <h3>
      <i class="far fa-check-square"></i>
      Editing lesson
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show lesson', course_lesson_path(@course, @lesson) %> |
    <%= link_to 'Back to course', course_path(@lesson.course) %>
  </div>
</div>
<%= link_to 'Courses', courses_path %> |
<%= link_to @lesson.course.title, course_path(@lesson.course) %> |
<%= link_to @lesson.title, course_lesson_path(@course, @lesson) %> |
Editing lesson

<p></p>

<div class="card">
  <div class="card-header">
    <h3>
      <i class="far fa-check-square"></i>
      Editing lesson
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form' %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show lesson', course_lesson_path(@course, @lesson) %> |
    <%= link_to 'Back to course', course_path(@lesson.course) %>
  </div>
</div>

app/views/lessons/index.html.erb
<h1>Listing lessons</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Course</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.title %></td>
        <td><%= lesson.content %></td>
        <td><%= lesson.course %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Lesson', new_lesson_path %>

app/views/lessons/new.html.erb
<h1>New lesson</h1>
<%= render 'form' %>
<%= link_to 'Back', course_path(@course)%>

app/views/lessons/show.html.erb
<%= link_to 'Courses', courses_path %> <br/>
<%= link_to @lesson.course.title, course_path(@lesson.course) %> <br/>
<%= link_to @lesson.title, course_lesson_path(@course, @lesson) %>

<p></p>

<%= render 'lessons/lesson', lesson: @lesson %>

<%= link_to 'Back to course', course_path(@lesson.course) %>