config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :enrollments do
    get :my_students, on: :collection
  end
  resources :courses do
    get :purchased, :pending_review, :created, on: :collection
    resources :lessons
    resources :enrollments, only: [:new, :create]  # This handles new and create actions for enrollments
  end

  resources :users, only: [:index, :edit, :show, :update]

  root "home#index"
  get 'home/home'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="bg-dark text-white py-3">
  <div class="container">
    <div class="row">
      <!-- Column 1: Copyright -->
      <div class="col-md-4 mb-2">
        <p>&copy; <%= Time.now.year %> CoursePlatform Sp. z o.o.</p>
        <div class="d-flex align-items-center">
          <i class="fa fa-envelope mr-2"></i>
          <%= mail_to 'yashm@outlook.com', 'Contact Us', class: 'text-white' %>
        </div>
      </div>

      <!-- Column 3: About Us -->
      <div class="col-md-4 mb-2">
        <h6>About Us</h6>
        <%= link_to 'Teach on CoursePlatform', new_course_path, class: 'btn btn-sm btn-primary' %>
      </div>
    </div>
  </div>
</footer>
<br>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
      <%= content_tag :div, msg, id: "flash_#{name}" %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">EduTech</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- Home Link -->
        <li class="nav-item">
          <%= link_to home_home_path, class: 'nav-link' do %>
            <i class="fas fa-home"></i> Home
          <% end %>
        </li>

        <!-- Courses Link -->
        <li class="nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <i class="fas fa-book"></i> Courses
          <% end %>
        </li>

        <!-- Activity Dropdown 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="activityDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-bars"></i> Activity
          </a>
          <ul class="dropdown-menu" aria-labelledby="activityDropdown">
            <li>
              <%= link_to enrollments_path, class: 'dropdown-item' do %>
                <i class="fas fa-lock-open"></i> Enrollments
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'dropdown-item' do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to activity_path, class: 'dropdown-item' do %>
                <i class="fas fa-bell"></i> Activities
              <% end %>
            </li>
          </ul>
        </li>
        -->

        <% if current_user %>
          <!-- Student Dropdown -->
          <% if current_user.has_role?(:student) %>
            <li class="nav-item dropdown">
              <a id="studentDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-graduation-cap"></i> Learn
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="studentDropdown">
                <%= link_to purchased_courses_path, class: "dropdown-item" do %>
                  <i class="fa fa-graduation-cap"></i> Purchased Courses
                <% end %>
                <%= link_to pending_review_courses_path, class: "dropdown-item" do %>
                  <i class="fa fa-star"></i> Pending Review
                <% end %>
              </div>
            </li>
          <% end %>




        <!-- Teacher Dropdown -->
     <% if current_user.has_role?(:teacher) %>
  <li class="nav-item dropdown">
    <a id="teacherDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-chalkboard-teacher"></i>
      Teach
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="teacherDropdown">
      <%= link_to new_course_path, class: "dropdown-item" do %>
        <i class="fa fa-graduation-cap"></i>
        <i class="fa fa-plus"></i>
        New Course
      <% end %>
      <%= link_to created_courses_path, class: "dropdown-item" do %>
        <i class="fa fa-graduation-cap"></i>
        My courses
      <% end %>
      <%= link_to my_students_enrollments_path, class: "dropdown-item" do %>
        <i class="fa fa-users"></i>
        My students
      <% end %>
    </div>
  </li>
<% end %>


        <!-- Admin Dropdown -->
        <% if current_user.has_role?(:admin) %>
          <li class="nav-item dropdown">
            <a id="adminDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="fa fa-cog"></span>
              Admin
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="adminDropdown">
              <%= link_to users_path, class: "dropdown-item" do %>
                <span class="fa fa-users"></span>
                Users
              <% end %>
              <%= link_to enrollments_path, class: "dropdown-item" do %>
                <span class="fa fa-lock-open"></span>
                Enrollments
              <% end %>
              <%= link_to activity_path, class: "dropdown-item" do %>
                <span class="fa fa-bell"></span>
                Activity
              <% end %>
              <%= link_to analytics_path, class: "dropdown-item" do %>
                <span class="fa fa-bell"></span>
                Analytics
              <% end %>
            </div>
          </li>
        <% end %>

        <!-- User Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i> <%= current_user.email %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
            <li>
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <i class="fa fa-user"></i> My Profile
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
                <i class="fas fa-cog"></i> Account Settings
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' do %>
                <i class="fas fa-sign-out-alt"></i> Logout
              <% end %>
            </li>
          </ul>
        </li>
        <% else %>
        <!-- Sign Up / Log In -->
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>

      <!-- Search Form at the End -->
      <form class="d-flex ms-auto" role="search">
        <input class="form-control form-control-sm me-2" type="search" placeholder="Search" aria-label="Search" style="max-width: 150px;">
        <button class="btn btn-sm btn-outline-success" type="submit">
          <i class="fas fa-search"></i> Search
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Edutech" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body> 
    
    <%= render "layouts/messages" %>
    <div>
      <% if current_user %>
      <%= render "layouts/navbar" %>
      <% end%>

      <%= yield %>  
      <%#= render "layouts/footer", class: "fixed-bottom" %>
    </div>
    
  </body>